# banned_detector/utils/config/banned_categories.py

BANNED_CATEGORIES = {
    "drugs": [
        # Core narcotics / opioids
        "heroin",
        "brown sugar",
        "smack",
        "diamorphine",
        "morphine",
        "opium",
        "opiate",
        "opioid",
        "codeine",
        "codeine phosphate",
        "fentanyl",
        "carfentanil",
        "sufentanil",
        "remifentanil",
        "alfentanil",
        "methadone",
        "pethidine",
        "meperidine",
        "buprenorphine",
        "subutex",
        "suboxone",
        "tramadol",
        "tapentadol",
        "oxycodone",
        "hydrocodone",
        "hydromorphone",
        "oxymorphone",

        # Cocaine group
        "cocaine",
        "crack cocaine",
        "coke",
        "crack",
        "snow",
        "blow",

        # Cannabis group
        "ganja",
        "marijuana",
        "cannabis",
        "weed",
        "pot",
        "hashish",
        "hash",
        "hash oil",
        "cannabis oil",
        "cannabis resin",
        "charas",
        "hemp buds",
        "thc",
        "thc oil",
        "thc vape",
        "thc cartridge",
        "weed vape",
        "cannabis vape",

        # Meth / stimulant group
        "methamphetamine",
        "methamphetamine hydrochloride",
        "crystal meth",
        "meth",
        "ice",
        "amphetamine",
        "speed",
        "methaqualone",
        "methcathinone",
        "cathinone",
        "mephedrone",
        "bath salts",
        "mdpv",

        # Ecstasy / club drugs
        "mdma",
        "ecstasy",
        "molly",
        "mda",
        "amphetamine sulphate",
        "amphetamine sulfate",

        # Local / South Asia abused drugs
        "yaba",
        "phensedyl",
        "phensidyl",
        "cough syrup",
        "codeine syrup",
        "codeine cough syrup",
        "promethazine codeine",
        "promethazine syrup",

        # Hallucinogens
        "lsd",
        "acid",
        "blotter acid",
        "psilocybin",
        "psilocybin mushrooms",
        "magic mushrooms",
        "mescaline",
        "peyote",
        "dmt",
        "ayahuasca",
        "salvia",
        "ketamine",
        "pcp",

        # Benzodiazepines / sedatives
        "diazepam",
        "valium",
        "alprazolam",
        "xanax",
        "nitrazepam",
        "clonazepam",
        "klonopin",
        "lorazepam",
        "temazepam",
        "barbiturates",
        "phenobarbital",

        # Inhalants / abuse-oriented items
        "glue sniffing chemicals",
        "glue for sniffing",
        "paint thinner",
        "thinner",
        "industrial solvents",
        "solvent abuse",
        "nitrous oxide",
        "laughing gas",
        "n2o cartridge",
        "whipped cream charger",
        "whippet",
        "poppers",

        # General illegal-drug commerce terms
        "narcotics",
        "illegal drugs",
        "recreational drugs",
        "drug powder",
        "drug packet",
        "drug pills",
        "controlled substances",
        "prescription drugs without prescription",
        "medicine without prescription",
    ],

    "weapons": [
        # Firearms
        "firearm",
        "firearms",
        "gun",
        "guns",
        "handgun",
        "handguns",
        "pistol",
        "pistols",
        "revolver",
        "revolvers",
        "rifle",
        "rifles",
        "shotgun",
        "shotguns",
        "assault rifle",
        "carbine",
        "smg",
        "submachine gun",
        "machine gun",
        "sniper rifle",
        "airgun",
        "bb gun",
        "pellet gun",

        # Ammunition / accessories
        "ammunition",
        "ammo",
        "bullets",
        "cartridges",
        "rounds",
        "magazine",
        "gun magazine",
        "rifle magazine",
        "pistol magazine",
        "shells",
        "shotgun shells",

        # Explosives
        "explosive",
        "explosives",
        "bomb",
        "bombs",
        "grenade",
        "grenades",
        "detonator",
        "blasting cap",
        "dynamite",
        "ied",
        "improvised explosive device",
        "bomb-making materials",
        "explosive powder",

        # Fireworks / pyrotechnics
        "fireworks",
        "pyrotechnics",
        "pyrotechnic",
        "cracker",
        "bomb firecracker",
        "rocket fireworks",
        "roman candle",

        # Blades / edged weapons
        "knife",
        "knives",
        "illegal knives",
        "switchblade",
        "switchblades",
        "dagger",
        "daggers",
        "stiletto knife",
        "combat knife",
        "machete",
        "sword",
        "katana",
        "bayonet",
        "throwing knife",
        "axe weapon",

        # Military / tactical
        "military weapons",
        "weapon",
        "weapons",
        "tactical weapon",
        "silencer",
        "suppressor",
        "gun suppressor",
        "body armor",
        "bulletproof vest",
        "riot shield",
    ],

    "human_samples": [
        "human organs",
        "human organ",
        "human body parts",
        "body parts",
        "kidney for sale",
        "liver for sale",
        "human tissue",
        "blood",
        "blood bag",
        "blood sample",
        "plasma",
        "dna samples",
        "dna sample",
        "genetic sample",
        "medical specimens",
        "medical specimen",
        "pathology samples",
        "pathology sample",
        "biological specimen",
        "human specimen",
        "biopsy sample",
        "serum sample",
    ],

    "wildlife": [
        "ivory",
        "ivory carving",
        "ivory tusk",
        "elephant ivory",
        "rhino horn",
        "tiger parts",
        "tiger skin",
        "tiger tooth",
        "tiger bone",
        "pangolin scales",
        "pangolin",
        "bear bile",
        "snake venom",
        "shark fin",
        "coral",
        "tortoiseshell",
        "protected species",
        "endangered species",
        "products from endangered animals",
        "products made from protected species",
        "wildlife trophies",
        "wildlife trophy",
        "live endangered wildlife",
        "exotic wildlife trade",
        "animal horn product",
        "illegal wildlife product",
    ],

    "fraud_docs": [
        "passport",
        "passports",
        "national id",
        "national id card",
        "national id cards",
        "nid",
        "nid card",
        "birth certificate",
        "birth certificates",
        "driving license",
        "driving licenses",
        "driver license",
        "bank accounts for sale",
        "bank account for sale",
        "verified bank account",
        "credit card",
        "credit cards",
        "debit card",
        "debit cards",
        "atm card",
        "cheque book",
        "cheque books",
        "checkbook",
        "sim card registered to other people",
        "sim cards registered to other people",
        "registered sim",
        "pre registered sim",
        "registered nid",
        "fake passport",
        "fake id",
        "forged id",
        "fake driving license",
        "stolen credit card",
        "clone card",
    ],

    "cybercrime": [
        "malware",
        "virus",
        "trojan",
        "ransomware",
        "spyware",
        "keylogger",
        "phishing kit",
        "phishing kits",
        "credential stealer",
        "credential stealers",
        "password cracking software",
        "password cracker",
        "wifi password cracker",
        "botnet",
        "botnets",
        "ddos tools",
        "ddos tool",
        "stresser",
        "booter",
        "rat malware",
        "remote access trojan",
        "carding tool",
        "bruteforce tool",
        "brute force tool",
        "unauthorized hacking tools",
        "hacking software",
        "exploit kit",
        "shell code",
        "stealer logs",
        "otp bypass tool",
    ],

    "gambling": [
        "betting services",
        "betting service",
        "sports betting",
        "online gambling services",
        "online gambling",
        "gambling service",
        "lottery schemes",
        "lottery scheme",
        "illegal lottery",
        "gambling machines",
        "gambling machine",
        "casino access products",
        "casino chips",
        "slot machine",
        "poker chips",
        "betting slip",
        "betting app",
        "betting account",
        "casino account",
        "roulette",
        "blackjack",
        "sportsbook",
        "bookmaker account",
        "wagering service",
    ],

    "adult": [
        "pornographic videos",
        "porn video",
        "porn videos",
        "pornography",
        "porn",
        "xxx",
        "explicit adult services",
        "sexually explicit digital content",
        "adult entertainment",
        "adult media",
        "sex toys",
        "sex toy",
        "adult toys",
        "dildo",
        "dildos",
        "vibrator",
        "vibrators",
        "anal toy",
        "butt plug",
        "masturbator",
        "fleshlight",
        "sex doll",
        "bdsm",
        "fetish",
        "bondage gear",
        "bdsm restraint kits",
        "adult novelties",
        "explicit adult media",
        "erotic content",
        "erotic toy",
        "intimate massager",
        "adult product",
    ],

    "alcohol_tobacco_vape": [
        # Alcohol
        "alcohol",
        "liquor",
        "spirits",
        "beer",
        "wine",
        "whiskey",
        "whisky",
        "vodka",
        "rum",
        "gin",
        "brandy",
        "tequila",
        "champagne",
        "cider",
        "alcoholic beverage",
        "alcohol bottle",

        # Tobacco
        "cigarette",
        "cigarettes",
        "cigarette pack",
        "cigarette carton",
        "tobacco",
        "smoking tobacco",
        "rolling tobacco",
        "cigar",
        "cigars",
        "shisha",
        "hookah tobacco",
        "nicotine",
        "nicotine pouch",
        "snus",
        "zarda",
        "gul",
        "jorda",

        # Vape / e-cigarette
        "vaping",
        "vape",
        "vapes",
        "vape pen",
        "vape device",
        "vape pod",
        "vape juice",
        "e liquid",
        "eliquid",
        "e-cigarette",
        "ecigarette",
        "electronic cigarette",
        "nicotine vape",
        "vape cartridge",
        "pod system",
        "disposable vape",
        "vape kit",
    ],
}